BEGIN;

CREATE TABLE IF NOT EXISTS ham_ops.bad_geocode (
	id integer GENERATED BY DEFAULT AS IDENTITY DEFAULT nextval('ham_ops.bad_geocode_id_seq'::regclass) NOT NULL,
	unique_system_identifier integer GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY(id)
);

COMMIT;