BEGIN;

CREATE TABLE IF NOT EXISTS ham_ops.geocoded_entity_data (
	unique_system_identifier numeric(9,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	latitude numeric GENERATED BY DEFAULT AS IDENTITY,
	longitude numeric GENERATED BY DEFAULT AS IDENTITY,
	rating integer GENERATED BY DEFAULT AS IDENTITY,
	geom geometry(Point,4326) GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY(unique_system_identifier)
);

COMMIT;