BEGIN;

CREATE TABLE IF NOT EXISTS ham_ops.entity_data (
	record_type character(2) GENERATED BY DEFAULT AS IDENTITY,
	unique_system_identifier numeric(9,0) GENERATED BY DEFAULT AS IDENTITY,
	uls_file_number character(14) GENERATED BY DEFAULT AS IDENTITY,
	ebf_number character varying(30) GENERATED BY DEFAULT AS IDENTITY,
	call_sign character(10) GENERATED BY DEFAULT AS IDENTITY,
	entity_type character(2) GENERATED BY DEFAULT AS IDENTITY,
	licensee_id character(9) GENERATED BY DEFAULT AS IDENTITY,
	entity_name character varying(200) GENERATED BY DEFAULT AS IDENTITY,
	first_name character varying(40) GENERATED BY DEFAULT AS IDENTITY,
	mi character(20) GENERATED BY DEFAULT AS IDENTITY,
	last_name character varying(40) GENERATED BY DEFAULT AS IDENTITY,
	suffix character(3) GENERATED BY DEFAULT AS IDENTITY,
	phone character(10) GENERATED BY DEFAULT AS IDENTITY,
	fax character(10) GENERATED BY DEFAULT AS IDENTITY,
	email character varying(50) GENERATED BY DEFAULT AS IDENTITY,
	street_address character varying(60) GENERATED BY DEFAULT AS IDENTITY,
	city character varying(40) GENERATED BY DEFAULT AS IDENTITY,
	state character(2) GENERATED BY DEFAULT AS IDENTITY,
	zip_code character(9) GENERATED BY DEFAULT AS IDENTITY,
	po_box character varying(40) GENERATED BY DEFAULT AS IDENTITY,
	attention_line character varying(100) GENERATED BY DEFAULT AS IDENTITY,
	sgin character(3) GENERATED BY DEFAULT AS IDENTITY,
	fcc_registration_number character(10) GENERATED BY DEFAULT AS IDENTITY,
	applicant_type_code character(1) GENERATED BY DEFAULT AS IDENTITY,
	applicant_type_code_other character varying(40) GENERATED BY DEFAULT AS IDENTITY,
	status_code character(1) GENERATED BY DEFAULT AS IDENTITY,
	status_date date GENERATED BY DEFAULT AS IDENTITY,
	three_point_seven_ghz_license_type character(1) GENERATED BY DEFAULT AS IDENTITY,
	linked_unique_system_identifier numeric(9,0) GENERATED BY DEFAULT AS IDENTITY,
	linked_call_sign character(10) GENERATED BY DEFAULT AS IDENTITY,
	id integer GENERATED BY DEFAULT AS IDENTITY DEFAULT nextval('ham_ops.entity_data_id_seq'::regclass) NOT NULL,
	PRIMARY KEY(id)
);

COMMIT;